Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider",
            "name": "ArrayDataProvider",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003Apaginate\u0028\u0029",
            "name": "paginate",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#method_paginate"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003AgetEntity\u0028\u0029",
            "name": "getEntity",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#method_getEntity"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003A\u0024entityHandlers",
            "name": "entityHandlers",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#property_entityHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#property_data"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003A\u0024paginatedData",
            "name": "paginatedData",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#property_paginatedData"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\ArrayDataProvider\u003A\u003A\u0024info",
            "name": "info",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-ArrayDataProvider.html#property_info"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\Interfaces\\DataProviderFormInterface",
            "name": "DataProviderFormInterface",
            "summary": "Interface\u0020for\u0020DataProvider\u0020objects.\u0020DataProvider\u0020is\u0020class\u0020that\u0020from\nany\u0020source\u0020get\u0020data,\u0020convert\u0020it\u0020to\u0020array\u0020that\u0020can\u0020be\u0020handled\u0020by\nEntityInterface.\u0020The\u0020DataProviderInterface\u0020have\u0020getEntity\u0028\u0029\u0020method,\nthat\u0020returns\u0020EntityInterface,\u0020that\u0020can\u0020be\u0020rendered",
            "url": "classes/Core-Entify-DataProvider-Interfaces-DataProviderFormInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\Interfaces\\DataProviderPaginatedInterface",
            "name": "DataProviderPaginatedInterface",
            "summary": "Interface\u0020for\u0020DataProvider\u0020objects.\u0020DataProvider\u0020is\u0020class\u0020that\u0020from\nany\u0020source\u0020get\u0020data,\u0020convert\u0020it\u0020to\u0020array\u0020that\u0020can\u0020be\u0020handled\u0020by\nEntityInterface.\u0020The\u0020DataProviderInterface\u0020have\u0020getEntity\u0028\u0029\u0020method,\nthat\u0020returns\u0020EntityInterface,\u0020that\u0020can\u0020be\u0020rendered",
            "url": "classes/Core-Entify-DataProvider-Interfaces-DataProviderPaginatedInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\Interfaces\\DataProviderPaginatedInterface\u003A\u003Apaginate\u0028\u0029",
            "name": "paginate",
            "summary": "",
            "url": "classes/Core-Entify-DataProvider-Interfaces-DataProviderPaginatedInterface.html#method_paginate"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary",
            "name": "DefaultFilterLibrary",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_check\u0028\u0029",
            "name": "filter_check",
            "summary": "Check\u0020with\u0020own\u0020function.\u0020Run\u0020callable\u0020that\u0020return\u0020true\nif\u0020done\u0020or\u0020string\u0020with\u0020error",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_check"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_filter\u0028\u0029",
            "name": "filter_filter",
            "summary": "filter\u0020value,\u0020with\u0020own\u0020callable,\u0020that\u0020get\u0020value\u0020and\u0020return\u0020modified\u0020value",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_filter"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_escape\u0028\u0029",
            "name": "filter_escape",
            "summary": "Escape\u0020entity\u0020with\u0020htmlspecialchars",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_escape"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_allowed\u0028\u0029",
            "name": "filter_allowed",
            "summary": "Apply\u0020strip_tags",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_allowed"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_convert\u0028\u0029",
            "name": "filter_convert",
            "summary": "Convert\u0020to\u0020some\u0020type",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_convert"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_array\u0028\u0029",
            "name": "filter_array",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_array"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_bool\u0028\u0029",
            "name": "filter_bool",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_bool"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_callable\u0028\u0029",
            "name": "filter_callable",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_callable"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_float\u0028\u0029",
            "name": "filter_float",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_float"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_int\u0028\u0029",
            "name": "filter_int",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_int"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_null\u0028\u0029",
            "name": "filter_null",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_null"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_object\u0028\u0029",
            "name": "filter_object",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_object"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_resource\u0028\u0029",
            "name": "filter_resource",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_resource"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003Afilter_string\u0028\u0029",
            "name": "filter_string",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_filter_string"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "Get\u0020errors\u0020array\u0020or\u0020null\u0020if\u0020no\u0020errors",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003A\u0024rulesName",
            "name": "rulesName",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#property_rulesName"
        },                {
            "fqsen": "\\Core\\Entify\\DefaultFilterLibrary\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "",
            "url": "classes/Core-Entify-DefaultFilterLibrary.html#property_errors"
        },                {
            "fqsen": "\\Core\\Entify\\Entification",
            "name": "Entification",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html"
        },                {
            "fqsen": "\\Core\\Entify\\Entification\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\Entification\u003A\u003AgetArrayProvider\u0028\u0029",
            "name": "getArrayProvider",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html#method_getArrayProvider"
        },                {
            "fqsen": "\\Core\\Entify\\Entification\u003A\u003AgetFormProvider\u0028\u0029",
            "name": "getFormProvider",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html#method_getFormProvider"
        },                {
            "fqsen": "\\Core\\Entify\\Entification\u003A\u003AresolveRules\u0028\u0029",
            "name": "resolveRules",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html#method_resolveRules"
        },                {
            "fqsen": "\\Core\\Entify\\Entification\u003A\u003A\u0024loader",
            "name": "loader",
            "summary": "",
            "url": "classes/Core-Entify-Entification.html#property_loader"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault",
            "name": "EntityHandlerDefault",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_handle"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Aprocessor_validate\u0028\u0029",
            "name": "processor_validate",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_processor_validate"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Aprocessor_checkNotExists\u0028\u0029",
            "name": "processor_checkNotExists",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_processor_checkNotExists"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Aprocessor_normalize\u0028\u0029",
            "name": "processor_normalize",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_processor_normalize"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Aprocessor_filters\u0028\u0029",
            "name": "processor_filters",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_processor_filters"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003Aprocessor_hide\u0028\u0029",
            "name": "processor_hide",
            "summary": "Hide\u0020some\u0020entity\u0020fields\u0020if\u0020it\u0020have\u0020hide\u0020attribute",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_processor_hide"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003AaddErrors\u0028\u0029",
            "name": "addErrors",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_addErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Get\u0020options\u0020object\nWith\u0020them,\u0020you\u0020can\u0020set\u0020up\u0020your\u0020entity\nby\u0020calling\u0020methods",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024filterLibrary",
            "name": "filterLibrary",
            "summary": "Library\u0020with\u0020specific\u0020filters\nthat\u0020run\u0020by\u0020DefaultHandler",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_filterLibrary"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024options",
            "name": "options",
            "summary": "Options\u0020object\u0020that\u0020contain\u0020bool\u0020options\u0020for\u0020DefaultHandlerInterface",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_options"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "Validator\u0020that\u0020verify\u0020data\u0020using\u0020rules",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_validator"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024rulesName",
            "name": "rulesName",
            "summary": "Name\u0020of\u0020rules\u0020model",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_rulesName"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024info",
            "name": "info",
            "summary": "Some\u0020info\u0020from\u0020DataProviderInterface",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_info"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "Array\u0020with\u0020error\u0020pessages\nArray\u0020of\u0020string\u0020data",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_errors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlerDefault\u003A\u003A\u0024rules",
            "name": "rules",
            "summary": "Verified\u0020array\u0020with\u0020rules",
            "url": "classes/Core-Entify-EntityHandlerDefault.html#property_rules"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers",
            "name": "EntityHandlers",
            "summary": "",
            "url": "classes/Core-Entify-EntityHandlers.html"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020have\u0020one\u0020parameter\u0020\u002D\u0020default\u0020handler.",
            "url": "classes/Core-Entify-EntityHandlers.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AregisterHandler\u0028\u0029",
            "name": "registerHandler",
            "summary": "Register\u0020oen\u0020Entity\u0020handler\u0020as\u0020callable",
            "url": "classes/Core-Entify-EntityHandlers.html#method_registerHandler"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AregisterClassHandler\u0028\u0029",
            "name": "registerClassHandler",
            "summary": "Register\u0020own\u0020Entity\u0020handler",
            "url": "classes/Core-Entify-EntityHandlers.html#method_registerClassHandler"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AbypassHandler\u0028\u0029",
            "name": "bypassHandler",
            "summary": "Mark\u0020handler\u0020as\u0020bypassed",
            "url": "classes/Core-Entify-EntityHandlers.html#method_bypassHandler"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020Field\u0020handlers\u0020for\u0020process",
            "url": "classes/Core-Entify-EntityHandlers.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Return\u0020options\u0020from\u0020default\u0020handler",
            "url": "classes/Core-Entify-EntityHandlers.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003AclearHandlerList\u0028\u0029",
            "name": "clearHandlerList",
            "summary": "Clear\u0020all\u0020handlers\u0020include\u0020default\u0020from\u0020handlers\u0020list\u0020to\u0020process\u0020entity",
            "url": "classes/Core-Entify-EntityHandlers.html#method_clearHandlerList"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003A\u0024defaultHandler",
            "name": "defaultHandler",
            "summary": "Default\u0020handler\u0020for\u0020handling\u0020entities",
            "url": "classes/Core-Entify-EntityHandlers.html#property_defaultHandler"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "Handler\u0020list\u0020for\u0020processing\u0020entities.\u0020By\u0020default\u0020it\u0020contain\none\u0020default\u0020handler",
            "url": "classes/Core-Entify-EntityHandlers.html#property_handlers"
        },                {
            "fqsen": "\\Core\\Entify\\EntityHandlers\u003A\u003A\u0024bypassHandlers",
            "name": "bypassHandlers",
            "summary": "List\u0020of\u0020handlers\u0020that\u0020need\u0020to\u0020be\u0020bepassed",
            "url": "classes/Core-Entify-EntityHandlers.html#property_bypassHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain",
            "name": "EntityMain",
            "summary": "",
            "url": "classes/Core-Entify-EntityMain.html"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "EntityMain\u0020class\u0020created\u0020inside\u0020DataProvider.",
            "url": "classes/Core-Entify-EntityMain.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020entity\u0020with\u0020EntityRendererInterface",
            "url": "classes/Core-Entify-EntityMain.html#method_render"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "Export\u0020this\u0020entity\u0020to\u0020array",
            "url": "classes/Core-Entify-EntityMain.html#method_export"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "Get\u0020error\u0020list\u0020array",
            "url": "classes/Core-Entify-EntityMain.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Get\u0020default\u0020handler\u0020configuration\u0020object",
            "url": "classes/Core-Entify-EntityMain.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003AmergeErrors\u0028\u0029",
            "name": "mergeErrors",
            "summary": "",
            "url": "classes/Core-Entify-EntityMain.html#method_mergeErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Core-Entify-EntityMain.html#method_process"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "Get\u0020entity\u0020info\u0020if\u0020exists.\u0020For\u0020example\u0020it\u0020can\u0020be\u0020pagination\u0020info",
            "url": "classes/Core-Entify-EntityMain.html#method_getInfo"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020handlers\u0020storage",
            "url": "classes/Core-Entify-EntityMain.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003A\u0024entityHandlers",
            "name": "entityHandlers",
            "summary": "Entity\u0020handlers\u0020list\u0020object\nIt\u0020give\u0020entity\u0020handlers\u0020list\u0020for\u0020processing.",
            "url": "classes/Core-Entify-EntityMain.html#property_entityHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003A\u0024data",
            "name": "data",
            "summary": "Data\u0020\u002D\u0020the\u0020data\u0020from\u0020DataProvider",
            "url": "classes/Core-Entify-EntityMain.html#property_data"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003A\u0024info",
            "name": "info",
            "summary": "Some\u0020info\u0020from\u0020DataProvider",
            "url": "classes/Core-Entify-EntityMain.html#property_info"
        },                {
            "fqsen": "\\Core\\Entify\\EntityMain\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "Error\u0020messages\u0020list",
            "url": "classes/Core-Entify-EntityMain.html#property_errors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions",
            "name": "EntityOptions",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AsetDeleteRedundant\u0028\u0029",
            "name": "setDeleteRedundant",
            "summary": "Delete\u0020redundant\u0020fields\u0020from\u0020entity",
            "url": "classes/Core-Entify-EntityOptions.html#method_setDeleteRedundant"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AsetSkipValidation\u0028\u0029",
            "name": "setSkipValidation",
            "summary": "Skip\u0020processing\u0020validator",
            "url": "classes/Core-Entify-EntityOptions.html#method_setSkipValidation"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AsetReturnIfValidationErrors\u0028\u0029",
            "name": "setReturnIfValidationErrors",
            "summary": "If\u0020true,\u0020the\u0020result\u0020will\u0020be\u0020return\nif\u0020validator\u0020say\u0020any\u0020errors",
            "url": "classes/Core-Entify-EntityOptions.html#method_setReturnIfValidationErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AsetReturnIfNotExistsErrors\u0028\u0029",
            "name": "setReturnIfNotExistsErrors",
            "summary": "Return\u0020result\u0020if\u0020some\u0020fields\u0020from\u0020rules\u0020not\u0020exists\u0020in\u0020entities\nof\u0020some\u0020errors\u0020before.\u0020In\u0020this\u0020case\u0020will\u0020be\u0020skipped\u0020validation\nand\u0020filters\u0020if\u0020true\u003B",
            "url": "classes/Core-Entify-EntityOptions.html#method_setReturnIfNotExistsErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AsetSkipFilters\u0028\u0029",
            "name": "setSkipFilters",
            "summary": "Skip\u0020processing\u0020filters",
            "url": "classes/Core-Entify-EntityOptions.html#method_setSkipFilters"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003AgetBoolOption\u0028\u0029",
            "name": "getBoolOption",
            "summary": "Get\u0020some\u0020bool\u0020option",
            "url": "classes/Core-Entify-EntityOptions.html#method_getBoolOption"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003A\u0024returnIfNotExistsErrors",
            "name": "returnIfNotExistsErrors",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html#property_returnIfNotExistsErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003A\u0024returnIfValidationErrors",
            "name": "returnIfValidationErrors",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html#property_returnIfValidationErrors"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003A\u0024skipFilters",
            "name": "skipFilters",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html#property_skipFilters"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003A\u0024skipValidation",
            "name": "skipValidation",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html#property_skipValidation"
        },                {
            "fqsen": "\\Core\\Entify\\EntityOptions\u003A\u003A\u0024deleteRedundant",
            "name": "deleteRedundant",
            "summary": "",
            "url": "classes/Core-Entify-EntityOptions.html#property_deleteRedundant"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory",
            "name": "HandlerFactory",
            "summary": "Factory\u0020for\u0020get\u0020handlers\u0020list\u0020for\u0020processing\u0020entity",
            "url": "classes/Core-Entify-HandlerFactory.html"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-HandlerFactory.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020set\u0020of\u0020handlers\u0020for\u0020process\u0020entity\u0020rules",
            "url": "classes/Core-Entify-HandlerFactory.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003AgetHandler\u0028\u0029",
            "name": "getHandler",
            "summary": "",
            "url": "classes/Core-Entify-HandlerFactory.html#method_getHandler"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "",
            "url": "classes/Core-Entify-HandlerFactory.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003AgetValidator\u0028\u0029",
            "name": "getValidator",
            "summary": "",
            "url": "classes/Core-Entify-HandlerFactory.html#method_getValidator"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003AgetFilterLibrary\u0028\u0029",
            "name": "getFilterLibrary",
            "summary": "",
            "url": "classes/Core-Entify-HandlerFactory.html#method_getFilterLibrary"
        },                {
            "fqsen": "\\Core\\Entify\\HandlerFactory\u003A\u003A\u0024rules",
            "name": "rules",
            "summary": "Rules\u0020object.\u0020It\u0020contain\u0020rules\u0020for\u0020validate\u0020and\u0020process\u0020Entity\nRules\u0020can\u0020be\u0020classes\u0020or\u0020arrays\u0020or\u0020json\u0020or\u0020xml\u0020files\u0020etc.",
            "url": "classes/Core-Entify-HandlerFactory.html#property_rules"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\DataProviderInterface",
            "name": "DataProviderInterface",
            "summary": "Interface\u0020for\u0020DataProvider\u0020objects.\u0020DataProvider\u0020is\u0020class\u0020that\u0020from\nany\u0020source\u0020get\u0020data,\u0020convert\u0020it\u0020to\u0020array\u0020that\u0020can\u0020be\u0020handled\u0020by\nEntityInterface.\u0020The\u0020DataProviderInterface\u0020have\u0020getEntity\u0028\u0029\u0020method,\nthat\u0020returns\u0020EntityInterface,\u0020that\u0020can\u0020be\u0020rendered",
            "url": "classes/Core-Entify-Interfaces-DataProviderInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\DataProviderInterface\u003A\u003AgetEntity\u0028\u0029",
            "name": "getEntity",
            "summary": "Get\u0020ready\u0020entity\u0020that\u0020can\u0020be\u0020rendered\u0020by\u0020EntityRenderer\u0020interface",
            "url": "classes/Core-Entify-Interfaces-DataProviderInterface.html#method_getEntity"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlerDefaultInterface",
            "name": "EntityHandlerDefaultInterface",
            "summary": "Interface\u0020for\u0020default\u0020entity\u0020handler.\u0020You\u0020can\u0020plug\u0020own\u0020handlers,\nbut\u0020by\u0020default\u0020Entify\u0020have\u0020default\u0020handler.",
            "url": "classes/Core-Entify-Interfaces-EntityHandlerDefaultInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlerDefaultInterface\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Get\u0020options\u0020object\nWith\u0020them,\u0020you\u0020can\u0020set\u0020up\u0020your\u0020entity\nby\u0020calling\u0020methods",
            "url": "classes/Core-Entify-Interfaces-EntityHandlerDefaultInterface.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlerInterface",
            "name": "EntityHandlerInterface",
            "summary": "Interface\u0020for\u0020own\u0020handlers,\u0020that\u0020can\u0020be\u0020used\u0020with\u0020DefaultHandler.",
            "url": "classes/Core-Entify-Interfaces-EntityHandlerInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlerInterface\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020data\u0020in\u0020entity",
            "url": "classes/Core-Entify-Interfaces-EntityHandlerInterface.html#method_handle"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlerInterface\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "Get\u0020errors\u0020that\u0020you\u0020can\u0020get\u0020while\u0020processing\u0020entity\u0020data",
            "url": "classes/Core-Entify-Interfaces-EntityHandlerInterface.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface",
            "name": "EntityHandlersInterface",
            "summary": "Interface\u0020hor\u0020Handlers\u0020list\u0020object.\u0020This\u0020object\u0020can\u0020edit\u0020and\u0020get\nlist\u0020of\u0020handlers\u0020that\u0020process\u0020entity",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AregisterHandler\u0028\u0029",
            "name": "registerHandler",
            "summary": "Register\u0020new\u0020handler",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_registerHandler"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AregisterClassHandler\u0028\u0029",
            "name": "registerClassHandler",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_registerClassHandler"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Get\u0020default\u0020handler\u0020options\u0020object",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AclearHandlerList\u0028\u0029",
            "name": "clearHandlerList",
            "summary": "Clear\u0020all\u0020handlers\u0020list,\u0020with\u0020default",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_clearHandlerList"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AbypassHandler\u0028\u0029",
            "name": "bypassHandler",
            "summary": "Bypass\u0020some\u0020handler\u0020by\u0020key",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_bypassHandler"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityHandlersInterface\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020handler\u0020list\nThis\u0020method\u0020return\u0020array\u0020of\u0020EnrityHandlerInterface",
            "url": "classes/Core-Entify-Interfaces-EntityHandlersInterface.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface",
            "name": "EntityInterface",
            "summary": "Main\u0020entity\u0020interface.\u0020You\u0020can\u0020get\u0020it\u0020from\u0020DataProviderInterface\u0020object.",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "Export\u0020this\u0020entity\u0020to\u0020array",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_export"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020entity\u0020with\u0020EntityRendererInterface",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_render"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "Get\u0020entity\u0020info\u0020if\u0020exists.\u0020For\u0020example\u0020it\u0020can\u0020be\u0020pagination\u0020info",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_getInfo"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003AgetOptions\u0028\u0029",
            "name": "getOptions",
            "summary": "Get\u0020default\u0020handler\u0020configuration\u0020object",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_getOptions"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020handlers\u0020storage",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityInterface\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "Get\u0020error\u0020list\u0020array",
            "url": "classes/Core-Entify-Interfaces-EntityInterface.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface",
            "name": "EntityOptionsInterface",
            "summary": "Options\u0020object\u0020for\u0020default\u0020handler.",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AsetDeleteRedundant\u0028\u0029",
            "name": "setDeleteRedundant",
            "summary": "Delete\u0020redundant\u0020fields\u0020from\u0020entity",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_setDeleteRedundant"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AsetSkipValidation\u0028\u0029",
            "name": "setSkipValidation",
            "summary": "Skip\u0020processing\u0020validator",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_setSkipValidation"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AsetSkipFilters\u0028\u0029",
            "name": "setSkipFilters",
            "summary": "Skip\u0020processing\u0020filters",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_setSkipFilters"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AsetReturnIfNotExistsErrors\u0028\u0029",
            "name": "setReturnIfNotExistsErrors",
            "summary": "Return\u0020result\u0020if\u0020some\u0020fields\u0020from\u0020rules\u0020not\u0020exists\u0020in\u0020entities\nof\u0020some\u0020errors\u0020before.\u0020In\u0020this\u0020case\u0020will\u0020be\u0020skipped\u0020validation\nand\u0020filters\u0020if\u0020true\u003B",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_setReturnIfNotExistsErrors"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AsetReturnIfValidationErrors\u0028\u0029",
            "name": "setReturnIfValidationErrors",
            "summary": "If\u0020true,\u0020the\u0020result\u0020will\u0020be\u0020return\nif\u0020validator\u0020say\u0020any\u0020errors",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_setReturnIfValidationErrors"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityOptionsInterface\u003A\u003AgetBoolOption\u0028\u0029",
            "name": "getBoolOption",
            "summary": "Get\u0020some\u0020bool\u0020option",
            "url": "classes/Core-Entify-Interfaces-EntityOptionsInterface.html#method_getBoolOption"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityRendererInterface",
            "name": "EntityRendererInterface",
            "summary": "Entity\u0020renderer\u0020interface.\u0020You\u0020can\u0020write\u0020your\u0020own\u0020renderer",
            "url": "classes/Core-Entify-Interfaces-EntityRendererInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\EntityRendererInterface\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Render\u0020entity",
            "url": "classes/Core-Entify-Interfaces-EntityRendererInterface.html#method_generate"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface",
            "name": "FilterLibraryInterface",
            "summary": "Filter\u0020library.\u0020This\u0020methods\u0020run\u0020while\u0020working\u0020DefaultHandlerInterface.",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_check\u0028\u0029",
            "name": "filter_check",
            "summary": "Check\u0020with\u0020own\u0020function.\u0020Run\u0020callable\u0020that\u0020return\u0020true\nif\u0020done\u0020or\u0020string\u0020with\u0020error",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_check"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_filter\u0028\u0029",
            "name": "filter_filter",
            "summary": "filter\u0020value,\u0020with\u0020own\u0020callable,\u0020that\u0020get\u0020value\u0020and\u0020return\u0020modified\u0020value",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_filter"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_escape\u0028\u0029",
            "name": "filter_escape",
            "summary": "Escape\u0020entity\u0020with\u0020htmlspecialchars",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_escape"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_allowed\u0028\u0029",
            "name": "filter_allowed",
            "summary": "Apply\u0020strip_tags",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_allowed"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_convert\u0028\u0029",
            "name": "filter_convert",
            "summary": "Convert\u0020to\u0020some\u0020type",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_convert"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_bool\u0028\u0029",
            "name": "filter_bool",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_bool"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_string\u0028\u0029",
            "name": "filter_string",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_string"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_int\u0028\u0029",
            "name": "filter_int",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_int"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_float\u0028\u0029",
            "name": "filter_float",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_float"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_array\u0028\u0029",
            "name": "filter_array",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_array"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_null\u0028\u0029",
            "name": "filter_null",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_null"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_object\u0028\u0029",
            "name": "filter_object",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_object"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003Afilter_callable\u0028\u0029",
            "name": "filter_callable",
            "summary": "",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_filter_callable"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\FilterLibraryInterface\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "Get\u0020errors\u0020array\u0020or\u0020null\u0020if\u0020no\u0020errors",
            "url": "classes/Core-Entify-Interfaces-FilterLibraryInterface.html#method_getErrors"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\HandlerFactoryInterface",
            "name": "HandlerFactoryInterface",
            "summary": "The\u0020factory\u0020that\u0020give\u0020us\u0020the\u0020handlers\u0020list\u0020for\u0020processing\u0020entity",
            "url": "classes/Core-Entify-Interfaces-HandlerFactoryInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\HandlerFactoryInterface\u003A\u003AgetHandlers\u0028\u0029",
            "name": "getHandlers",
            "summary": "Get\u0020set\u0020of\u0020handlers\u0020for\u0020process\u0020entity\u0020rules",
            "url": "classes/Core-Entify-Interfaces-HandlerFactoryInterface.html#method_getHandlers"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesInterface",
            "name": "RulesInterface",
            "summary": "Object\u0020for\u0020store\u0020rules\u0020for\u0020processing\u0020entities",
            "url": "classes/Core-Entify-Interfaces-RulesInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesInterface\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Get\u0020model\u0020name\u0020of\u0020rules",
            "url": "classes/Core-Entify-Interfaces-RulesInterface.html#method_getName"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesInterface\u003A\u003AgetRules\u0028\u0029",
            "name": "getRules",
            "summary": "Get\u0020rules\u0020array",
            "url": "classes/Core-Entify-Interfaces-RulesInterface.html#method_getRules"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesLoaderInterface",
            "name": "RulesLoaderInterface",
            "summary": "Loader\u0020for\u0020rules.\u0020It\u0020load\u0020rules\u0020from\u0020source\u0020and\u0020give\u0020us\u0020RulesInterface",
            "url": "classes/Core-Entify-Interfaces-RulesLoaderInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesLoaderInterface\u003A\u003AgetRules\u0028\u0029",
            "name": "getRules",
            "summary": "Get\u0020rules\u0020object",
            "url": "classes/Core-Entify-Interfaces-RulesLoaderInterface.html#method_getRules"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesModelInterface",
            "name": "RulesModelInterface",
            "summary": "This\u0020interface\u0020for\u0020users\u0020that\u0020store\u0020rules\u0020in\u0020model\u0020classes.",
            "url": "classes/Core-Entify-Interfaces-RulesModelInterface.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces\\RulesModelInterface\u003A\u003AgetRules\u0028\u0029",
            "name": "getRules",
            "summary": "Get\u0020array\u0020with\u0020rules",
            "url": "classes/Core-Entify-Interfaces-RulesModelInterface.html#method_getRules"
        },                {
            "fqsen": "\\Core\\Entify\\Rules",
            "name": "Rules",
            "summary": "",
            "url": "classes/Core-Entify-Rules.html"
        },                {
            "fqsen": "\\Core\\Entify\\Rules\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020constructor\u0020arguments\u0020\u002D\u0020rules\u0020model\u0020name\u0020and\u0020array\u0020of\u0020rules",
            "url": "classes/Core-Entify-Rules.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\Rules\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Get\u0020model\u0020name\u0020of\u0020rules",
            "url": "classes/Core-Entify-Rules.html#method_getName"
        },                {
            "fqsen": "\\Core\\Entify\\Rules\u003A\u003AgetRules\u0028\u0029",
            "name": "getRules",
            "summary": "Get\u0020rules\u0020array",
            "url": "classes/Core-Entify-Rules.html#method_getRules"
        },                {
            "fqsen": "\\Core\\Entify\\Rules\u003A\u003A\u0024rulesName",
            "name": "rulesName",
            "summary": "Rules\u0020model\u0020name",
            "url": "classes/Core-Entify-Rules.html#property_rulesName"
        },                {
            "fqsen": "\\Core\\Entify\\Rules\u003A\u003A\u0024rulesData",
            "name": "rulesData",
            "summary": "Array\u0020with\u0020verified\u0020rules",
            "url": "classes/Core-Entify-Rules.html#property_rulesData"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderClass",
            "name": "RulesLoaderClass",
            "summary": "",
            "url": "classes/Core-Entify-RulesLoaderClass.html"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderClass\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Entify-RulesLoaderClass.html#method___construct"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderClass\u003A\u003AfindModel\u0028\u0029",
            "name": "findModel",
            "summary": "Find\u0020the\u0020class\u0020\u0028RulesModelInterface\u0029\u0020with\u0020rules\u0020data",
            "url": "classes/Core-Entify-RulesLoaderClass.html#method_findModel"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderClass\u003A\u003AgetRules\u0028\u0029",
            "name": "getRules",
            "summary": "Get\u0020rules\u0020object",
            "url": "classes/Core-Entify-RulesLoaderClass.html#method_getRules"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderClass\u003A\u003A\u0024namespace",
            "name": "namespace",
            "summary": "Namespace\u0020for\u0020finding\u0020rules\u0020models",
            "url": "classes/Core-Entify-RulesLoaderClass.html#property_namespace"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderTrait",
            "name": "RulesLoaderTrait",
            "summary": "You\u0020can\u0020use\u0020this\u0020trait\u0020for\u0020own\u0020model\u0020rules\u0020loaders.",
            "url": "classes/Core-Entify-RulesLoaderTrait.html"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderTrait\u003A\u003AcheckModelData\u0028\u0029",
            "name": "checkModelData",
            "summary": "Check\u0020model\u0020data\u0020for\u0020correct\u0020info.",
            "url": "classes/Core-Entify-RulesLoaderTrait.html#method_checkModelData"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderTrait\u003A\u003A\u0024availableParams",
            "name": "availableParams",
            "summary": "All\u0020available\u0020params\u0020for\u0020every\u0020field\u0020in\u0020rules",
            "url": "classes/Core-Entify-RulesLoaderTrait.html#property_availableParams"
        },                {
            "fqsen": "\\Core\\Entify\\RulesLoaderTrait\u003A\u003A\u0024needParams",
            "name": "needParams",
            "summary": "Required\u0020params\u0020for\u0020every\u0020field\u0020in\u0020rules",
            "url": "classes/Core-Entify-RulesLoaderTrait.html#property_needParams"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider",
            "name": "DataProvider",
            "summary": "",
            "url": "namespaces/core-entify-dataprovider.html"
        },                {
            "fqsen": "\\Core\\Entify\\DataProvider\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-entify-dataprovider-interfaces.html"
        },                {
            "fqsen": "\\Core\\Entify",
            "name": "Entify",
            "summary": "",
            "url": "namespaces/core-entify.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        },                {
            "fqsen": "\\Core\\Entify\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-entify-interfaces.html"
        }            ]
);
